language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
script:
- npm rebuild node-sass
- npm run build
after_success:
- if ( [ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ] ) && [ "$TRAVIS_REPO_SLUG"
  == "dhis2/gis-app" ]  &&  [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then mvn clean
  deploy --settings deploy/settings.xml && exit 0; fi
env:
  global:
  - secure: Xd8basVh6mxVBvvhjSyZam28jCfaXdi0JiPQtBCKF3O+x+ioZzTRBi0/c3FRRdEXvG1WBTqJyDE7kniyNvktVR3ZN4izK2H3Wp1Pyeq2JTF0QLuS9LPrs6NU/MvKVGdiF3eS5PydCRuG4w1WbJQ56TvjU3wOqgU1sr04scXFCwmJ79lsQqVRHiSrAxHK9DHvDApUnN2iLypGvps87n9F5qzbKYvqlmcOj+avPByVWOIvjf7e4bImeSOfay3bcpsGqNoymbEBLb8Q4zNpRdEDlOZc7y2IX8CA8pnH7rUPUeq5sOO3x0rm/sUTE47buUDJPsbvkMgtQNDSoQjIFw+Z5WELgd53ZcTlKs0s+M3JowipfP8cIjKVDwZ7Y8APYXyqHQ4ytT1JxWsWxqo2lIvfOSiEjcJzD2loXtOvHpDODUrJcnCG7Z1mj4EchIsc/vh6fGH5jB7ErlNcHGMKd56gpufvc73MNL9VsYgTbBvn2D2c3ttBPjkcxJPiIpvYUGtVuEErjkY3zs/6vfZoyq1rpPelEFKKqRz7roY/b/EoBBUZVxizPO6U3v+fCz0zoznm8t4H5xFlTa88hx4Vsus9+YEA36OXYBnAy7ZrZ25wdnnFoTjSd7uxdk04kqeWD68qQrr/e4JIIwyMpHMuaWRTY/G1/5NMRc0noT+LW4ehPgo=
  - secure: CqJYMGpRbf4xiYRKq4+biKy6TXbVbEvWcEVw2zTaVGmDfT4Cpb9VLXmNS9GINxGcvDQRk4OL3kzY2057E0lcNh6TjvoE+S7N8x42dbOzeetDp6nMniQYuS+IknZ/qgduk9ksb+yX6Q3D4d8BjEkQ3arcMAQNpEnUNYqowHUrIaK5+et7lXvqjJgTT4PExvIgLqgo9eCgp9hulxD0SJ1uoXhtI0Dyf6bjkj06LTcodi9VHM61QKFM6SiMzz7AlcU2SM52Hv9DDC+FFBIVB0a2+eroH6o74wQwMLqzp1odI+zaFP1x4ZH2H6NNY1k0I83C2dZO5BLrK+ZqZWyNzncj2omu1kHCJ5fxjgDVV3D6/WLb6jgX+r2+y9JP2JTAg1jrThq9EsW1HMtynfXmNA4EAdwzJOz6kU4555fMVMStiC/5KMhA2TzKhfnLWM0r/iuAhebn/WVfL/R8TovreBzyeh85dab7me/VEoIDxGdZeVjOeExNNr/mo1xYS3hfeOwDncRn5FJNRvgR+dLlCmU1DftMwhI1WO+eZJm1ztR81L9/yI9WTiWY78pSuAvQGXyCWaTIASkd2R8KH03vTpVGi9oOd2mcg3Lk4lCvn+TeV4vquWKXp7N3YbVVkOudAKahWxtiPlbqssuejlbM61HmxrBnuJVvi1SAbQFlhCIsvt0=
