/* MAP */
export const MAP_SET = 'MAP_SET';
export const MAP_CLEAR = 'MAP_CLEAR'; // Needed?

/* MAP */
export const MAP_CONTEXT_MENU_OPEN = 'MAP_CONTEXT_MENU_OPEN';
export const MAP_CONTEXT_MENU_CLOSE = 'MAP_CONTEXT_MENU_CLOSE';
export const MAP_COORDINATE_OPEN = 'MAP_COORDINATE_OPEN';
export const MAP_COORDINATE_CLOSE = 'MAP_COORDINATE_CLOSE';

/* BASEMAP */
export const BASEMAP_SELECTED = 'BASEMAP_SELECTED';
export const BASEMAP_TOGGLE_EXPAND = 'BASEMAP_TOGGLE_EXPAND';
export const BASEMAP_TOGGLE_VISIBILITY = 'BASEMAP_TOGGLE_VISIBILITY';
export const BASEMAP_CHANGE_OPACITY = 'BASEMAP_CHANGE_OPACITY';

/* OVERLAY */
export const OVERLAY_ADD = 'OVERLAY_ADD';
export const OVERLAY_CHANGE_OPACITY = 'OVERLAY_CHANGE_OPACITY';
export const OVERLAY_EDIT = 'OVERLAY_EDIT';
export const OVERLAY_EDIT_SUCCESS = 'OVERLAY_EDIT_SUCCESS';
export const OVERLAY_EDIT_FAILURE = 'OVERLAY_EDIT_FAILURE';
export const OVERLAY_GET = 'OVERLAY_GET';
export const OVERLAY_LOAD_REQUESTED = 'OVERLAY_LOAD_REQUESTED';
export const OVERLAY_LOAD_SUCCESS = 'OVERLAY_LOAD_SUCCESS';
export const OVERLAY_LOAD_ERROR = 'OVERLAY_LOAD_ERROR';
export const OVERLAY_REMOVE = 'OVERLAY_REMOVE';
export const OVERLAY_SORT = 'OVERLAY_SORT';
export const OVERLAY_TOGGLE_EXPAND = 'OVERLAY_TOGGLE_EXPAND';
export const OVERLAY_TOGGLE_VISIBILITY = 'OVERLAY_TOGGLE_VISIBILITY';
export const OVERLAY_UPDATE = 'OVERLAY_UPDATE';
export const OVERLAY_DRILL = 'OVERLAY_DRILL';
export const OVERLAYS_DIALOG_OPEN_REQUESTED = 'OVERLAYS_DIALOG_OPEN_REQUESTED';
export const OVERLAYS_DIALOG_CLOSE_REQUESTED = 'OVERLAYS_DIALOG_CLOSE_REQUESTED';

/* FAVORITE */
export const FAVORITE_LOAD = 'FAVORITE_LOAD';
export const FAVORITE_LOADING = 'FAVORITE_LOADING';
export const FAVORITE_LOAD_SUCCESS = 'FAVORITE_LOAD_SUCCESS';
export const FAVORITE_LOAD_ERROR = 'FAVORITE_LOAD_ERROR';
export const FAVORITES_DIALOG_OPEN_REQUESTED = 'FAVORITES_DIALOG_OPEN_REQUESTED';
export const FAVORITES_DIALOG_CLOSE_REQUESTED = 'FAVORITES_DIALOG_CLOSE_REQUESTED';

/* ORGANISATION UNIT */
export const ORGANISATION_UNIT_OPEN = 'ORGANISATION_UNIT_OPEN';
export const ORGANISATION_UNIT_CLOSE = 'ORGANISATION_UNIT_CLOSE';
export const ORGANISATION_UNIT_SELECT = 'ORGANISATION_UNIT_SELECT';
export const ORGANISATION_UNIT_UNSELECT = 'ORGANISATION_UNIT_UNSELECT';
export const ORGANISATION_UNIT_RELOCATE_START = 'ORGANISATION_UNIT_RELOCATE_START';
export const ORGANISATION_UNIT_RELOCATE_STOP = 'ORGANISATION_UNIT_RELOCATE_STOP';
export const ORGANISATION_UNIT_COORDINATE_CHANGE = 'ORGANISATION_UNIT_COORDINATE_CHANGE';
export const ORGANISATION_UNITS_FILTER = 'ORGANISATION_UNITS_FILTER';
export const ORGANISATION_UNITS_UNFILTER = 'ORGANISATION_UNITS_UNFILTER';

/* USER INTERFACE */
export const DATA_TABLE_OPEN_REQUESTED = 'DATA_TABLE_OPEN_REQUESTED';
export const DATA_TABLE_CLOSE_REQUESTED = 'DATA_TABLE_CLOSE_REQUESTED';

/* LOADING */
export const LOADING = 'LOADING';
export const LOADED = 'LOADED';


