/* MAP */
export const MAP_SET = 'MAP_SET';
export const MAP_CLEAR = 'MAP_CLEAR'; // Needed?
export const MAP_CONTEXT_MENU_OPEN = 'MAP_CONTEXT_MENU_OPEN';
export const MAP_CONTEXT_MENU_CLOSE = 'MAP_CONTEXT_MENU_CLOSE';
export const MAP_COORDINATE_OPEN = 'MAP_COORDINATE_OPEN';
export const MAP_COORDINATE_CLOSE = 'MAP_COORDINATE_CLOSE';

/* BASEMAP */
export const BASEMAP_ADD = 'BASEMAP_ADD';
export const BASEMAP_REMOVE = 'BASEMAP_REMOVE';
export const BASEMAP_SELECTED = 'BASEMAP_SELECTED';
export const BASEMAP_TOGGLE_EXPAND = 'BASEMAP_TOGGLE_EXPAND';
export const BASEMAP_TOGGLE_VISIBILITY = 'BASEMAP_TOGGLE_VISIBILITY';
export const BASEMAP_CHANGE_OPACITY = 'BASEMAP_CHANGE_OPACITY';

/* OVERLAY */
export const OVERLAY_ADD = 'OVERLAY_ADD';
export const OVERLAY_REMOVE = 'OVERLAY_REMOVE';
export const OVERLAY_CHANGE_OPACITY = 'OVERLAY_CHANGE_OPACITY';
export const OVERLAY_EDIT = 'OVERLAY_EDIT';
export const OVERLAY_EDIT_SUCCESS = 'OVERLAY_EDIT_SUCCESS';
export const OVERLAY_EDIT_FAILURE = 'OVERLAY_EDIT_FAILURE';
export const OVERLAY_CANCEL = 'OVERLAY_CANCEL';
export const OVERLAY_GET = 'OVERLAY_GET';
export const OVERLAY_LOAD_REQUESTED = 'OVERLAY_LOAD_REQUESTED';
export const OVERLAY_LOAD_SUCCESS = 'OVERLAY_LOAD_SUCCESS';
export const OVERLAY_LOAD_ERROR = 'OVERLAY_LOAD_ERROR';
export const OVERLAY_SORT = 'OVERLAY_SORT';
export const OVERLAY_TOGGLE_EXPAND = 'OVERLAY_TOGGLE_EXPAND';
export const OVERLAY_TOGGLE_VISIBILITY = 'OVERLAY_TOGGLE_VISIBILITY';
export const OVERLAY_UPDATE = 'OVERLAY_UPDATE';
export const OVERLAY_DRILL = 'OVERLAY_DRILL';
export const OVERLAYS_DIALOG_OPEN_REQUESTED = 'OVERLAYS_DIALOG_OPEN_REQUESTED';
export const OVERLAYS_DIALOG_CLOSE_REQUESTED = 'OVERLAYS_DIALOG_CLOSE_REQUESTED';

/* EXTERNAL LAYERS */
export const EXTERNAL_LAYERS_LOAD = 'EXTERNAL_LAYERS_LOAD';
export const EXTERNAL_LAYERS_LOAD_ERROR = 'EXTERNAL_LAYERS_LOAD_ERROR';
export const EXTERNAL_OVERLAY_ADD = 'EXTERNAL_OVERLAY_ADD';
export const EXTERNAL_OVERLAY_REMOVE = 'EXTERNAL_OVERLAY_REMOVE';

/* FAVORITE */
export const FAVORITE_LOAD = 'FAVORITE_LOAD';
export const FAVORITE_LOADING = 'FAVORITE_LOADING';
export const FAVORITE_LOAD_SUCCESS = 'FAVORITE_LOAD_SUCCESS';
export const FAVORITE_LOAD_ERROR = 'FAVORITE_LOAD_ERROR';
export const FAVORITES_DIALOG_OPEN_REQUESTED = 'FAVORITES_DIALOG_OPEN_REQUESTED';
export const FAVORITES_DIALOG_CLOSE_REQUESTED = 'FAVORITES_DIALOG_CLOSE_REQUESTED';

/* DATA TABLE */
export const DATA_TABLE_OPEN = 'DATA_TABLE_OPEN';
export const DATA_TABLE_CLOSE = 'DATA_TABLE_CLOSE';
export const DATA_TABLE_TOGGLE = 'DATA_TABLE_TOGGLE';
export const DATA_TABLE_RESIZE = 'DATA_TABLE_RESIZE';

/* DATA FILTER */
export const DATA_FILTER_SET = 'DATA_FILTER_SET';
export const DATA_FILTER_CLEAR = 'DATA_FILTER_CLEAR';

/* ORGANISATION UNIT */
export const ORGANISATION_UNIT_OPEN = 'ORGANISATION_UNIT_OPEN';
export const ORGANISATION_UNIT_CLOSE = 'ORGANISATION_UNIT_CLOSE';
export const ORGANISATION_UNIT_SELECT = 'ORGANISATION_UNIT_SELECT';
export const ORGANISATION_UNIT_UNSELECT = 'ORGANISATION_UNIT_UNSELECT';
export const ORGANISATION_UNIT_RELOCATE_START = 'ORGANISATION_UNIT_RELOCATE_START';
export const ORGANISATION_UNIT_RELOCATE_STOP = 'ORGANISATION_UNIT_RELOCATE_STOP';
export const ORGANISATION_UNIT_COORDINATE_CHANGE = 'ORGANISATION_UNIT_COORDINATE_CHANGE';

/* ABOUT DIALOG */
export const ABOUT_DIALOG_OPEN_REQUESTED = 'ABOUT_DIALOG_OPEN_REQUESTED';
export const ABOUT_DIALOG_CLOSE_REQUESTED = 'ABOUT_DIALOG_CLOSE_REQUESTED';

/* USER INTERFACE */
export const SCREEN_RESIZE = 'SCREEN_RESIZE';
export const LAYERS_PANEL_OPEN_REQUESTED = 'LAYERS_PANEL_OPEN_REQUESTED';
export const LAYERS_PANEL_CLOSE_REQUESTED = 'LAYERS_PANEL_CLOSE_REQUESTED';

/* LOADING */
export const LOADING = 'LOADING';
export const LOADED = 'LOADED';

/* SYSTEM SETTINGS */
export const SYSTEM_DATA_SET = 'SYSTEM_DATA_SET';

/* USER */
export const USER_SET = 'USER_SET';

/* PROGRAMS */
export const PROGRAMS_LOAD = 'PROGRAMS_LOAD';
export const PROGRAMS_LOAD_ERROR = 'PROGRAMS_LOAD_ERROR';
export const PROGRAMS_SET = 'PROGRAMS_SET';
export const PROGRAM_STAGES_LOAD = 'PROGRAM_STAGES_LOAD';
export const PROGRAM_STAGES_LOAD_ERROR = 'PROGRAM_STAGES_LOAD_ERROR';
export const PROGRAM_STAGES_SET = 'PROGRAM_STAGES_SET';
export const PROGRAM_ATTRIBUTES_LOAD = 'PROGRAM_ATTRIBUTES_LOAD';
export const PROGRAM_ATTRIBUTES_LOAD_ERROR = 'PROGRAM_ATTRIBUTES_LOAD_ERROR';
export const PROGRAM_ATTRIBUTES_SET = 'PROGRAM_ATTRIBUTES_SET';
export const PROGRAM_STAGE_DATA_ELEMENTS_LOAD = 'PROGRAM_STAGE_DATA_ELEMENTS_LOAD';
export const PROGRAM_STAGE_DATA_ELEMENTS_LOAD_ERROR = 'PROGRAM_STAGE_DATA_ELEMENTS_LOAD_ERROR';
export const PROGRAM_STAGE_DATA_ELEMENTS_SET = 'PROGRAM_STAGE_DATA_ELEMENTS_SET';

/* OPTION SETS */
export const OPTION_SET_ADD = 'OPTION_SET_ADD';

/* LAYER EDIT */
export const LAYER_EDIT_PROGRAM_SET = 'LAYER_EDIT_PROGRAM_SET';
export const LAYER_EDIT_PROGRAM_STAGE_SET = 'LAYER_EDIT_PROGRAM_STAGE_SET';
export const LAYER_EDIT_STYLE_DATA_ELEMENT_SET = 'LAYER_EDIT_STYLE_DATA_ELEMENT_SET';
export const LAYER_EDIT_STYLE_DATA_ELEMENT_OPTIONS_SET = 'LAYER_EDIT_STYLE_DATA_ELEMENT_OPTIONS_SET';
export const LAYER_EDIT_EVENT_CLUSTERING_SET = 'LAYER_EDIT_EVENT_CLUSTERING_SET';
export const LAYER_EDIT_EVENT_POINT_RADIUS_SET = 'LAYER_EDIT_EVENT_POINT_RADIUS_SET';
export const LAYER_EDIT_EVENT_POINT_COLOR_SET = 'LAYER_EDIT_EVENT_POINT_COLOR_SET';
