export const relativePeriods = [
    {id: 'THIS_WEEK', i18n: 'this_week'},
    {id: 'LAST_WEEK', i18n: 'last_week'},
    {id: 'LAST_4_WEEKS', i18n: 'last_4_weeks'},
    {id: 'LAST_12_WEEKS', i18n: 'last_12_weeks'},
    {id: 'LAST_52_WEEKS', i18n: 'last_52_weeks'},
    {id: 'THIS_MONTH', i18n: 'this_month'},
    {id: 'LAST_MONTH', i18n: 'last_month'},
    {id: 'LAST_3_MONTHS', i18n: 'last_3_months'},
    {id: 'LAST_6_MONTHS', i18n: 'last_6_months'},
    {id: 'LAST_12_MONTHS', i18n: 'last_12_months'},
    {id: 'THIS_BIMONTH', i18n: 'this_bimonth'},
    {id: 'LAST_BIMONTH', i18n: 'last_bimonth'},
    {id: 'LAST_6_BIMONTHS', i18n: 'last_6_bimonths'},
    {id: 'THIS_QUARTER', i18n: 'this_quarter'},
    {id: 'LAST_QUARTER', i18n: 'last_quarter'},
    {id: 'LAST_4_QUARTERS', i18n: 'last_4_quarters'},
    {id: 'THIS_SIX_MONTH', i18n: 'this_sixmonth'},
    {id: 'LAST_SIX_MONTH', i18n: 'last_sixmonth'},
    {id: 'LAST_2_SIX_MONTHS', i18n: 'last_2_sixmonths'},
    {id: 'THIS_FINANCIAL_YEAR', i18n: 'this_financial_year'},
    {id: 'LAST_FINANCIAL_YEAR', i18n: 'last_financial_year'},
    {id: 'LAST_5_FINANCIAL_YEARS', i18n: 'last_5_financial_years'},
    {id: 'THIS_YEAR', i18n: 'this_year'},
    {id: 'LAST_YEAR', i18n: 'last_year'},
    {id: 'LAST_5_YEARS', i18n: 'last_5_years'},
];